# Generated by Django 6.1.1 on 2026-09-28 20:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=150)),
                ('status', models.CharField(choices=[('Applied', 'Applied'), ('Phone Screen', 'Phone Screen'), ('Interview', 'Interview'), ('Offer', 'Offer'), ('Rejected', 'Rejected')], default='Applied', max_length=20)),
                ('applied_date', models.DateField()),
                ('initials', models.CharField(blank=True, max_length=2)),
                ('logo_style', models.CharField(blank=True, max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-applied_date'],
            },
        ),
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(max_length=200)),
                ('due_date', models.DateTimeField()),
                ('urgency', models.CharField(choices=[('overdue', 'Overdue'), ('today', 'Today'), ('soon', 'Soon'), ('later', 'Later')], default='later', max_length=20)),
                ('completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='application.application')),
            ],
            options={
                'ordering': ['due_date'],
            },
        ),
    ]
